// ESLint 10 is flat-config only; there is no .eslintrc fallback.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/coverage/**',
      '**/*.tsbuildinfo',
      // Generated by kysely-codegen. Regenerated, never hand-edited.
      'apps/api/src/db/generated.ts',
    ],
  },

  js.configs.recommended,

  // Type-aware linting. `projectService` lets typescript-eslint discover the
  // nearest tsconfig per file, which is what makes this work across a
  // workspace without listing every project path here.
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  // Node-side packages.
  {
    files: ['apps/api/**/*.ts', 'db/**/*.ts', 'packages/shared/**/*.ts'],
    languageOptions: { globals: globals.node },
  },

  // Browser-side package.
  {
    files: ['apps/dashboard/**/*.{ts,tsx}'],
    languageOptions: { globals: globals.browser },
  },

  // Config files are plain JS and are not part of any tsconfig.
  {
    files: ['**/*.js', '**/*.config.js'],
    ...tseslint.configs.disableTypeChecked,
    languageOptions: { globals: globals.node },
  },

  {
    rules: {
      // Money is integer santim. A float here is a bug, so unsafe numeric
      // coercion must be explicit.
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/restrict-template-expressions': [
        'error',
        { allowNumber: true },
      ],
      'no-console': ['error', { allow: ['warn', 'error'] }],
    },
  },

  // Must stay last: turns off every rule that fights Prettier.
  prettier,
);
