// ESLint 10 is flat-config only; there is no .eslintrc fallback.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/coverage/**',
      '**/*.tsbuildinfo',
      // Generated by kysely-codegen. Regenerated, never hand-edited.
      'db/src/generated.ts',
    ],
  },

  js.configs.recommended,

  // Type-aware linting, scoped to TypeScript only. Applying it to every file
  // makes ESLint try to find eslint.config.js in a tsconfig and fail with
  // "was not found by the project service".
  //
  // `projectService` discovers the nearest tsconfig per file, which is what
  // makes this work across the workspace without listing project paths here.
  {
    files: ['**/*.ts', '**/*.tsx'],
    extends: [...tseslint.configs.strictTypeChecked, ...tseslint.configs.stylisticTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Money is integer santim. A float here is a bug, so unsafe numeric
      // coercion must be explicit.
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/restrict-template-expressions': ['error', { allowNumber: true }],
      'no-console': ['error', { allow: ['warn', 'error'] }],
      // Express detects error middleware by ARITY, so the fourth parameter
      // must be declared even when unused. Leading underscore marks intent.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },

  // Node-side packages.
  {
    files: ['apps/api/**/*.ts', 'db/**/*.ts', 'packages/shared/**/*.ts'],
    languageOptions: { globals: globals.node },
  },

  // Browser-side package.
  {
    files: ['apps/dashboard/**/*.{ts,tsx}'],
    languageOptions: { globals: globals.browser },
  },

  // Plain JS config files are not part of any tsconfig.
  {
    files: ['**/*.js', '**/*.mjs'],
    languageOptions: { globals: globals.node },
  },

  // Operator scripts are run by hand and talk to the user through stdout.
  {
    files: ['scripts/**/*.mjs', 'scripts/**/*.js'],
    rules: { 'no-console': 'off' },
  },

  // Tests may assert that a fixture they just created exists. A wrong
  // assumption fails the test immediately and locally, which is the desired
  // behaviour; production code keeps the rule.
  {
    files: ['**/test/**/*.ts', '**/*.test.ts'],
    rules: { '@typescript-eslint/no-non-null-assertion': 'off' },
  },

  // Must stay last: turns off every rule that fights Prettier.
  prettier,
);
