import type { ExpoConfig } from 'expo/config';

/**
 * The brand navy, written out: Expo's config loader resolves @laqum/shared to
 * its built dist, so importing BRAND here would need a build first.
 * test/brand-config.test.ts asserts it equals BRAND_NAVY.
 */
const BRAND_NAVY = '#1f3f71';

/**
 * Dynamic Expo config.
 *
 * Replaces app.json so that secrets and per-machine values come from the
 * environment instead of the repository.
 *
 * THE MAP NEEDS NO KEY AT ALL. Google Maps Platform requires a billing
 * account with an international card, which is not available to this project,
 * so the map is MapLibre over OpenFreeMap tiles — no registration, no API
 * key, no account. See CLAUDE.md, "Map stack".
 */

/**
 * Where the app talks to.
 *
 * On a device this MUST be the dev machine's LAN address — `localhost` is the
 * phone. Passed through `extra` as well as the EXPO_PUBLIC_ variable so it is
 * visible in `expo config` when diagnosing a build.
 */
const apiUrl = process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:3000/v1';

/** EAS injects this; it is 'development' | 'preview' | 'production'. */
const profile = process.env.EAS_BUILD_PROFILE ?? 'development';
const isProduction = profile === 'production';

const config: ExpoConfig = {
  name: 'ላቁም?',
  slug: 'laqum',
  /*
   * The project belongs to the ORGANISATION, not to whoever is logged in.
   * Without `owner`, Expo tooling assumes the logged-in account (dagi-dev)
   * and the project id below would not match it. See extra.eas.projectId.
   */
  owner: 'dagisha-dev-works',
  version: '0.1.0',
  orientation: 'portrait',
  scheme: 'laqum',
  userInterfaceStyle: 'automatic',
  /*
   * THE ICON, THE SPLASH: NATIVE. They reach the phone only with the next EAS
   * build, which is the one that adds Firebase (Phase 5, push), by decision.
   * Every image is generated by scripts/brand/build.mjs from the one source
   * (docs/BRAND.md); none is edited by hand.
   *
   * iOS and legacy Android: the navy wordmark on white, opaque.
   */
  icon: './assets/brand/icon.png',
  // No `newArchEnabled`: SDK 57 removed it from ExpoConfig because the new
  // architecture is now the default and is no longer opt-in.

  android: {
    package: 'et.laqum.driver',
    /*
     * Adaptive icon: the wordmark inside the 66 dp safe circle of the 108 dp
     * canvas, so no launcher mask clips a glyph, on flat white. The
     * monochrome image is for Android 13+ themed icons, which use only its
     * alpha.
     */
    adaptiveIcon: {
      foregroundImage: './assets/brand/adaptive-foreground.png',
      monochromeImage: './assets/brand/adaptive-monochrome.png',
      backgroundColor: '#ffffff',
    },
    // No `edgeToEdgeEnabled`: prebuild warns it is no longer customisable,
    // because Android 16 makes edge-to-edge mandatory.
    //
    // No `config.googleMaps` either: MapLibre needs no key.
    permissions: ['ACCESS_FINE_LOCATION', 'ACCESS_COARSE_LOCATION', 'CAMERA'],
  },

  ios: {
    bundleIdentifier: 'et.laqum.driver',
    supportsTablet: false,
    infoPlist: {
      NSLocationWhenInUseUsageDescription:
        'Laqum checks you are close enough to the parking lot before holding a slot for you.',
      NSCameraUsageDescription:
        'Laqum shows your booking QR code; the camera is not used to record anything.',
      ...(isProduction
        ? {}
        : {
            /*
             * iOS equivalent of the Android cleartext allowance below, for
             * the same reason and with the same production exclusion. iOS is
             * UNTESTED — see CLAUDE.md, Phase 4 open items.
             */
            NSAppTransportSecurity: { NSAllowsLocalNetworking: true },
          }),
    },
  },

  plugins: [
    'expo-router',
    'expo-secure-store',
    /*
     * The native splash (Android 12+ SplashScreen API): static, the white mark
     * on flat brand navy, in both themes. The in-app intro (src/intro) takes
     * over from the same navy, so there is no flash between the two. The
     * image sits in a 288 dp box shown through a 192 dp circle; the mark is
     * generated to fit inside that circle.
     */
    [
      'expo-splash-screen',
      {
        image: './assets/brand/splash-icon.png',
        imageWidth: 192,
        resizeMode: 'contain',
        backgroundColor: BRAND_NAVY,
        dark: { image: './assets/brand/splash-icon.png', backgroundColor: BRAND_NAVY },
      },
    ],
    // Required for a development build; MapLibre is native and is not part of
    // the Expo SDK, so it does not work in Expo Go.
    '@maplibre/maplibre-react-native',
    [
      'expo-location',
      {
        locationWhenInUsePermission:
          'Laqum checks you are close enough to the parking lot before holding a slot for you.',
      },
    ],
    [
      'expo-build-properties',
      {
        android: {
          /*
           * CLEARTEXT HTTP TO THE DEV API — DEVELOPMENT AND PREVIEW ONLY.
           *
           * Android 9 (API 28) defaults `usesCleartextTraffic` to false, so a
           * release build silently refuses http:// and every request fails
           * with "Network request failed". The dev API is plain http on a LAN
           * address, so a build meant for device testing has to allow it.
           *
           * FALSE in production, explicitly. This is the setting that would
           * be genuinely dangerous to leave on in a shipped app, so it is
           * keyed off EAS_BUILD_PROFILE rather than left to a default, and
           * `expo prebuild` output is checked in DEVICE-TEST.md step 3a.
           */
          usesCleartextTraffic: !isProduction,
        },
      },
    ],
  ],

  experiments: { typedRoutes: true },

  extra: {
    apiUrl,
    eas: {
      /*
       * The EXISTING project @dagisha-dev-works/laqum. Literal, by decision
       * (CLAUDE.md, Phase 4 open items):
       *
       * - `eas init --id` cannot write into a dynamic config, so it cannot
       *   put this here itself;
       * - it is not a secret: it ships inside every APK;
       * - a literal reaches all three readers alike: eas-cli, the EAS build
       *   machine (which never sees a developer's shell), and Metro, which
       *   serves it to the app for push registration.
       *
       * Never remove it to "re-link": with no id, eas-cli prints
       * "EAS project not configured." and fetches or CREATES a project.
       */
      projectId: 'e886a245-6e7e-4e4f-8032-f28b92ec202c',
    },
  },
};

export default config;
