/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type BookingSource = "app" | "walk_in";

export type BookingStatus = "CANCELLED" | "CHECKED_IN" | "CHECKED_OUT" | "EXPIRED" | "OVERSTAY" | "PAID" | "PENDING_PAYMENT" | "RESERVED";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type PaymentKind = "deposit" | "final" | "refund";

export type PaymentProvider = "cash" | "chapa" | "telebirr";

export type PaymentStatus = "failed" | "pending" | "success" | "superseded";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "attendant" | "driver" | "operator_admin";

export interface BookingEvents {
  actor_id: string | null;
  at: Generated<Timestamp>;
  booking_id: string;
  from_status: BookingStatus | null;
  id: Generated<Int8>;
  note: string | null;
  to_status: BookingStatus;
}

export interface Bookings {
  amount_due_santim: number | null;
  checked_in_at: Timestamp | null;
  checked_out_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  hold_expires_at: Timestamp | null;
  id: Generated<string>;
  lot_id: string;
  planned_end_at: Timestamp | null;
  planned_minutes: number | null;
  qr_token: string | null;
  short_code: string | null;
  slot_id: string;
  source: BookingSource;
  status: BookingStatus;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
  vehicle_plate: string | null;
}

export interface Lots {
  address: string | null;
  block_minutes: Generated<number>;
  contact_phone: string;
  created_at: Generated<Timestamp>;
  deposit_amount_santim: Generated<number>;
  hold_minutes: Generated<number>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  latitude: number;
  longitude: number;
  max_booking_distance_m: Generated<number>;
  name: string;
  operator_id: string;
  overstay_rate_per_block_santim: number;
  payment_window_minutes: Generated<number>;
  rate_per_block_santim: number;
}

export interface LotStaff {
  lot_id: string;
  user_id: string;
}

export interface Operators {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  phone: string;
}

export interface OtpCodes {
  attempts: Generated<number>;
  code_hash: string;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  phone: string;
}

export interface Payments {
  amount_santim: number;
  booking_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: PaymentKind;
  provider: PaymentProvider;
  provider_payload: Json | null;
  recorded_by: string | null;
  status: Generated<PaymentStatus>;
  tx_ref: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PushTokens {
  created_at: Generated<Timestamp>;
  expo_push_token: string;
  id: Generated<string>;
  user_id: string;
}

export interface RefreshTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_id: string;
}

export interface Slots {
  app_bookable: Generated<boolean>;
  grid_col: number;
  grid_row: number;
  id: Generated<string>;
  in_service: Generated<boolean>;
  label: string;
  lot_id: string;
  zone: Generated<string>;
}

export interface SlotStatus {
  app_bookable: boolean | null;
  booking_id: string | null;
  display_status: string | null;
  grid_col: number | null;
  grid_row: number | null;
  hold_expires_at: Timestamp | null;
  in_service: boolean | null;
  label: string | null;
  lot_id: string | null;
  planned_end_at: Timestamp | null;
  slot_id: string | null;
  source: BookingSource | null;
  updated_at: Timestamp | null;
  vehicle_plate: string | null;
  zone: string | null;
}

export interface Users {
  created_at: Generated<Timestamp>;
  full_name: string | null;
  id: Generated<string>;
  phone: string;
  role: Generated<UserRole>;
}

export interface DB {
  booking_events: BookingEvents;
  bookings: Bookings;
  lot_staff: LotStaff;
  lots: Lots;
  operators: Operators;
  otp_codes: OtpCodes;
  payments: Payments;
  push_tokens: PushTokens;
  refresh_tokens: RefreshTokens;
  slot_status: SlotStatus;
  slots: Slots;
  users: Users;
}
